#!/bin/sh
if [ -f ./cocos2d/scripts/$1.py ]; then
    python ./cocos2d/scripts/$1.py "$2" "$3" "$4" "$5" "$6"
elif [ -f ./scripts/$1.py ]; then
    python ./scripts/$1.py "$2" "$3" "$4" "$5" "$6"
else
    echo "Unknown command : $1"
fi


